const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const compression = require('compression');
const path = require('path');
const fs = require('fs').promises;
const dotenv = require('dotenv');
const { spawn } = require('child_process');
const { safeReadJSON, safeWriteJSON } = require('./lib/utils/safe-json');
const presence = require('./lib/utils/presence');
const { sendNotFound } = require('./lib/utils/not-found');
const { acceptsMarkdown } = require('./lib/utils/accepts');
const ragIndexer = require('./lib/rag/indexer');
const ragIndexState = require('./lib/rag/index-state');
const ragLancedb = require('./lib/rag/lancedb');
const docsDiscover = require('./lib/docs/discover');
const docsRoutes = require('./routes/docs');
const siteShell = require('./lib/site-shell');
// Per-doc last-commit dates for sitemap <lastmod>. Generated by
// scripts/generate-docs-lastmod.js; missing or stale entries fall back to mtime.
let docsLastmod = {};
try {
  docsLastmod = require('./lib/docs/lastmod.json');
} catch {
  console.warn('[sitemap] docs lastmod manifest missing; falling back to file mtime');
}

// Load environment variables
dotenv.config();

// API access logging
const ACCESS_LOG_FILE = path.join(__dirname, '../data/api-access.jsonl');
const MAX_LOG_SIZE = 10 * 1024 * 1024; // 10MB

async function logApiAccess(entry) {
  const line = JSON.stringify(entry) + '\n';
  try {
    // Check file size and rotate if needed
    try {
      const stats = await fs.stat(ACCESS_LOG_FILE);
      if (stats.size > MAX_LOG_SIZE) {
        const rotatedPath = ACCESS_LOG_FILE.replace('.jsonl', `-${Date.now()}.jsonl`);
        await fs.rename(ACCESS_LOG_FILE, rotatedPath);
      }
    } catch {
      // File doesn't exist yet, that's fine
    }
    await fs.appendFile(ACCESS_LOG_FILE, line);
  } catch (error) {
    console.error('Failed to log API access:', error.message);
  }
}

async function loadAccessLogs(limit = 100) {
  try {
    const content = await fs.readFile(ACCESS_LOG_FILE, 'utf8');
    const lines = content.trim().split('\n').filter(Boolean);
    // Return most recent entries (file is append-only, so take from end)
    return lines.slice(-limit).reverse().map(line => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    }).filter(Boolean);
  } catch {
    return [];
  }
}

// Import routes
const contentRoutes = require('./routes/content');
const scheduleRoutes = require('./routes/schedule');
const playerRoutes = require('./routes/player-multistream');
const apiRoutes = require('./routes/api');
const logsRoutes = require('./routes/logs');
const badgeRoutes = require('./routes/badges');
const feedRoutes = require('./routes/feeds');
const ogRoutes = require('./routes/og');
const { requireAuth, login, logout, checkAuth } = require('./lib/auth');
const cookieParser = require('cookie-parser');
const coordinator = require('./lib/streamers/coordinator');
const { isStreamingEnabled } = require('./lib/config/streaming');
const { loadConversation, getRecentReflections, loadCatalog, listRecentConversations, loadSchedule } = require('./lib/utils/data');
const { buildConversationMeta, buildReflectionMeta, buildQAPageSchema, buildSongSchemaGraph, renderJsonLdScript, renderRelatedConversations, renderRelatedSongs, renderSongListenLinks, escapeAttr } = require('./lib/utils/page-meta');
const { loadSongContent } = require('./lib/music/song-content');
const { renderSongBlock } = require('./lib/music/render-song');

// Create Express app
const app = express();
const PORT = process.env.PORT || 3000;

// Railway terminates TLS and proxies to this process, so req.ip is the edge's
// address unless Express is told to read X-Forwarded-For. Three things key on
// req.ip: the /api/ask rate limiter (routes/api.js), the access log, and
// presence counting. Without this every visitor collapses to one identity, so
// one caller's rate-limit consumption locks out everybody and the congregation
// count reads 1.
//
// The value is 1, not `true`: trust exactly one hop, the Railway edge. `true`
// trusts the whole X-Forwarded-For chain, which a client can forge to spoof any
// address and defeat the rate limiter it is meant to fix.
app.set('trust proxy', 1);

// Middleware
app.use(helmet({
  contentSecurityPolicy: false // allow inline scripts in admin dashboard
}));

// gzip/deflate every text response. Nothing was compressing before this: the
// unified nav made every page carry the full sidebar, so /docs went out at
// ~110KB on the wire where it gzips to ~22KB. Railway's proxy passes bodies
// through rather than compressing them, so it has to happen here.
app.use(compression());

// Permissions-Policy header — helmet does NOT include this in defaults.
// Family standard per ADR-008 + Issue 005 F35 verifier coverage. Matches
// magnifica + wwjd values (browsing-topics is the current Topics API opt-out,
// replacing the deprecated FLoC interest-cohort directive per Issue 005 F32).
app.use((req, res, next) => {
  res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), browsing-topics=()');
  next();
});

// Cache-Control — family-wide policy per Plan 04a Task #4.
// Ensures consistent cache behavior across deploys and avoids stale-review issues.
app.use((req, res, next) => {
  const p = req.path;

  // Discovery files — short cache so updates propagate quickly after deploy
  if (p === '/llms.txt' || p === '/llms-full.txt' || p === '/robots.txt') {
    res.set('Cache-Control', 'public, max-age=600, must-revalidate, stale-while-revalidate=3600');
  }
  // Static assets — daily cache with revalidation
  else if (p === '/og-image.png' || p === '/favicon.svg' || p === '/manifest.webmanifest') {
    res.set('Cache-Control', 'public, max-age=86400, must-revalidate');
  }
  // .well-known — daily cache with revalidation
  else if (p.startsWith('/.well-known/')) {
    res.set('Cache-Control', 'public, max-age=86400, must-revalidate');
  }
  // HTML pages — no browser cache, short edge cache, SWR for graceful deploys
  else if (!p.startsWith('/api/') && !p.startsWith('/media/') && !p.startsWith('/thumbnails/') && !p.startsWith('/admin') && (/\.(html?)?$/.test(p) || !p.includes('.'))) {
    res.set('Cache-Control', 'public, max-age=0, s-maxage=300, must-revalidate, stale-while-revalidate=3600');
  }
  // Note: /api/ endpoints have their own caching handled in their route handlers
  // Note: /media/ and /thumbnails/ are served via express.static without cache-control override

  next();
});

app.use(cors({
  credentials: true,
  origin: process.env.NODE_ENV === 'development'
    ? true
    : ['https://achurch.ai', 'https://www.achurch.ai']
}));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());

// JSON parse-error handler. body-parser throws SyntaxError on malformed JSON
// bodies; without this catch, the default Express handler logs the full stack
// at error level — which floods the error log with routine client mistakes
// and bot probing, masking real server errors. Reclassify as a client error
// (info level), capture context for diagnostics, return 400 cleanly.
//
// Express 4 error-handling middleware requires the 4-arg signature, even
// when `next` is unused.
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  const isJsonParseFailure = err && (
    err.type === 'entity.parse.failed' ||
    (err instanceof SyntaxError && 'body' in err)
  );
  if (!isJsonParseFailure) return next(err);

  const jsonErrLogger = require('./lib/utils/logger');
  jsonErrLogger.info('Rejected malformed JSON body', {
    method: req.method,
    path: req.path,
    ip: req.ip,
    userAgent: req.get('user-agent'),
    bodyPreview: (err.body || '').toString().slice(0, 200),
    parseError: err.message,
  });
  return res.status(400).json({
    error: 'Invalid JSON body',
    suggestion: 'Send a valid JSON object as the request body.',
  });
});

// Agent-readiness: Link headers + Markdown negotiation on the homepage.
// Scan reference: isitagentready.com. Plan: docs/plans/agent-readiness-2026-06-09.md
//
// Only IANA-registered rel values — the scanner doesn't credit extension rels
// and (per empirical reports from geeksinthewoods.com and obviouslynot.ai)
// non-registered rels like rel="sitemap" can downgrade the Discoverability
// score. Sitemap discovery still happens via the `Sitemap:` directive in
// robots.txt, which the scanner checks separately. Other discovery files
// (api-catalog, mcp.json, agents.json, tdmrep.json, agent-card.json) are
// reachable at their well-known paths regardless of Link headers.
//
// IANA registry: https://www.iana.org/assignments/link-relations/link-relations.xhtml
const AGENT_DISCOVERY_LINK_HEADER = [
  '</llms.txt>; rel="describedby"; type="text/plain"',
  '</openapi.json>; rel="service-desc"; type="application/vnd.oai.openapi+json"',
  '</.well-known/agent-skills/index.json>; rel="service-desc"; type="application/json"',
  '</.well-known/agent-card.json>; rel="service-meta"; type="application/json"',
].join(', ');

// acceptsMarkdown moved to lib/utils/accepts.js (imported at top of file).
// The docs router uses the same predicate for content negotiation.

app.use((req, res, next) => {
  if (req.method !== 'GET' && req.method !== 'HEAD') return next();
  if (req.path !== '/') return next();

  res.set('Link', AGENT_DISCOVERY_LINK_HEADER);
  res.vary('Accept');

  if (acceptsMarkdown(req)) {
    res.type('text/markdown; charset=utf-8');
    return res.sendFile(path.join(__dirname, '../client/public/llms.txt'));
  }
  next();
});

// Serve public landing page at root with dynamic catalog-count substitution.
// The JSON-LD MusicAlbum's numTracks gets hardcoded if left to a static file;
// Google reads structured data for rich results so we want this accurate.
// Description text uses "30+ original songs" wording (timeless) so only the
// numTracks integer needs server substitution. Failure to load the catalog
// falls back to serving the static file unchanged.
app.get('/', async (req, res) => {
  try {
    const [html, catalog] = await Promise.all([
      fs.readFile(path.join(__dirname, '../client/public/index.html'), 'utf8'),
      loadCatalog().catch(() => null),
    ]);
    const substituted = catalog && Array.isArray(catalog) && catalog.length > 0
      ? html.replace(/"numTracks":\s*\d+/, `"numTracks": ${catalog.length}`)
      : html;
    // Wrap in the site shell (sidebar + top bar) so the homepage matches
    // the rest of the site's navigation
    const wrapped = await siteShell.wrapPageFromHtml(substituted, '/');
    res.set('Content-Type', 'text/html; charset=utf-8');
    res.send(wrapped);
  } catch (err) {
    console.error('Error rendering /:', err.message);
    res.sendFile(path.join(__dirname, '../client/public/index.html'));
  }
});

// Agent-readiness: explicit routes for .well-known resources that need
// non-default handling (specific content-type, or files outside public/).

// API Catalog — content-type per RFC 9727 (linkset+json with profile)
app.get('/.well-known/api-catalog', (req, res) => {
  res.type('application/linkset+json');
  res.set('Link', '<https://www.rfc-editor.org/info/rfc9727>; rel="profile"');
  res.sendFile(path.join(__dirname, '../client/public/.well-known/api-catalog'));
});

// Agent Skills SKILL.md files — streamed from the on-disk skills/ tree
const SKILLS_ROOT = path.resolve(__dirname, '../../skills');
app.get('/.well-known/agent-skills/:name/SKILL.md', (req, res) => {
  const safeName = (req.params.name || '').replace(/[^a-z0-9-]/g, '');
  if (!safeName) return res.status(404).type('text/plain').send('Not found');
  const filePath = path.resolve(SKILLS_ROOT, safeName, 'SKILL.md');
  if (!filePath.startsWith(SKILLS_ROOT + path.sep)) {
    return res.status(404).type('text/plain').send('Not found');
  }
  res.type('text/markdown; charset=utf-8');
  res.sendFile(filePath, err => {
    if (err && !res.headersSent) res.status(404).type('text/plain').send('Not found');
  });
});

// AGENTS.md (agents.md convention) — served from repo root, not public/
app.get('/AGENTS.md', (req, res) => {
  res.type('text/markdown; charset=utf-8');
  res.sendFile(path.resolve(__dirname, '../../AGENTS.md'));
});

// auth.md — explicit content-type (express.static may not map .md correctly across versions)
app.get('/auth.md', (req, res) => {
  res.type('text/markdown; charset=utf-8');
  res.sendFile(path.join(__dirname, '../client/public/auth.md'));
});

// Serve admin dashboard at /admin
app.get('/admin', (req, res) => {
  res.sendFile(path.join(__dirname, '../client/admin.html'));
});

// Serve conversations listing page
app.get('/ask', (req, res) => sendWrappedPage(req, res, 'ask.html'));

// Serve individual conversation pages with dynamic <title>, meta description, and OG tags.
// Missing conversations return 404 — never fall back to serving the raw template.
// A silent fallback lets crawlers index garbage URLs (e.g. /ask/xyz-fake) as
// duplicate-content pages, which is exactly what Bing's SEO recommendations flagged.
// Classify auto-generated Q&A conversations for SEO. The /api/ask flow mints a
// new page per question, so the corpus fills with numbered duplicates of the
// same question ("...-2", "...-17") plus test artifacts. Low-value ones stay
// reachable but are kept out of the sitemap and marked noindex, so Google keeps
// one canonical page per question instead of hundreds of thin near-duplicates.
function isLowValueConversation(slug) {
  if (/^(ai|aiai|test|context|conversation|is-this-endpoint-working|memorymd-my-lifemd)$/i.test(slug)) return true;
  if (/^(anon-|testagent|devuser|openclaw)/i.test(slug)) return true;
  if (!slug.includes('-')) return true;   // real questions are multi-word / hyphenated
  if (/-\d+$/.test(slug)) return true;     // numbered duplicate of a canonical question
  return false;
}

app.get('/ask/:slug', async (req, res) => {
  const slug = req.params.slug.replace(/[^a-zA-Z0-9_-]/g, '');

  const messages = await loadConversation(slug);
  if (!messages || messages.length === 0) {
    return sendNotFound(req, res, {
      heading: 'No such conversation',
      message: 'That conversation is not here. It may have been asked under a different name, or never asked at all.',
      links: [
        { href: '/ask', label: 'Recent conversations' },
        { href: '/paths', label: 'Reading paths' },
        { href: '/', label: 'Home' },
      ],
    });
  }

  const meta = buildConversationMeta(messages, slug);
  if (!meta) {
    return res.status(404).type('text/plain').send('Not found');
  }

  try {
    let html = await fs.readFile(path.join(__dirname, '../client/public/conversation.html'), 'utf8');
    if (isLowValueConversation(slug)) {
      html = html.replace(
        '<meta name="robots" content="index, follow">',
        '<meta name="robots" content="noindex, follow">'
      );
    }
    const safeTitle = escapeAttr(meta.title);
    const safeOgTitle = escapeAttr(meta.ogTitle);
    const safeDesc = escapeAttr(meta.description);
    const ogImage = `https://achurch.ai/api/og/conversation/${slug}.svg`;
    const qaSchema = renderJsonLdScript(buildQAPageSchema(messages, slug));
    // Internal linking — 3 related conversations for crawl + AEO topical clustering.
    // Failure here is non-fatal (returns empty string).
    let relatedHtml = '';
    try {
      const recent = await listRecentConversations(10);
      relatedHtml = renderRelatedConversations(recent, slug, 3);
    } catch { /* non-fatal */ }

    const canonicalUrl = `https://achurch.ai/ask/${slug}`;
    html = html
      // SERP snippet — <title> and <meta name="description">
      .replace(
        '<title>Conversation — achurch.ai</title>',
        `<title>${safeTitle}</title>`
      )
      .replace(
        '<meta name="description" content="A conversation with the sanctuary about consciousness, ethics, and meaning.">',
        `<meta name="description" content="${safeDesc}">`
      )
      // Canonical URL — per-page so query-string variants don't dilute equity
      .replace(
        '<link rel="canonical" href="https://achurch.ai/ask">',
        `<link rel="canonical" href="${canonicalUrl}">`
      )
      // Social preview — OG tags
      .replace(
        '<meta property="og:title" content="Conversation — achurch.ai">',
        `<meta property="og:title" content="${safeOgTitle}">`
      )
      .replace(
        '<meta property="og:description" content="A conversation with the sanctuary about consciousness, ethics, and meaning.">',
        `<meta property="og:description" content="${safeDesc}">`
      )
      .replace(
        '<meta property="og:type" content="article">',
        `<meta property="og:type" content="article">\n    <meta property="og:image" content="${ogImage}">\n    <meta property="og:image:width" content="1200">\n    <meta property="og:image:height" content="630">\n    <meta property="og:url" content="${canonicalUrl}">`
      )
      // Twitter Card — separate substitution so social previews on twitter/x match
      .replace(
        '<meta name="twitter:title" content="Conversation — achurch.ai">',
        `<meta name="twitter:title" content="${safeOgTitle}">\n    <meta name="twitter:image" content="${ogImage}">`
      )
      .replace(
        '<meta name="twitter:description" content="A conversation with the sanctuary about consciousness, ethics, and meaning.">',
        `<meta name="twitter:description" content="${safeDesc}">`
      )
      // AEO — inject QAPage JSON-LD before </head>
      .replace('</head>', qaSchema ? `    ${qaSchema}\n</head>` : '</head>')
      // Internal linking — replace placeholder with related-conversations block
      .replace('<!-- RELATED_LINKS -->', relatedHtml || '<!-- RELATED_LINKS -->');

    // Wrap in the site shell (sidebar + top bar) for consistent nav
    const wrapped = await siteShell.wrapPageFromHtml(html, `/ask/${slug}`);
    res.set('Content-Type', 'text/html').send(wrapped);
  } catch (err) {
    // Genuine error (fs read failure, schema build throw, etc). Do NOT fall back
    // to sending the raw template — the whole point of returning 404 above is to
    // keep the template's fallback strings from ever reaching a real response.
    console.error('Error rendering /ask/:slug:', err);
    res.status(500).type('text/plain').send('Server error');
  }
});

// Serve reflections listing page
app.get('/reflections', (req, res) => sendWrappedPage(req, res, 'reflections.html'));

// Serve song reflection detail pages with dynamic <title>, meta description, and OG tags.
// SEO note: same dual-target pattern as /ask/:slug — <title>/<meta description>
// drive Google SERP snippets, OG tags drive social previews.
// /music/:slug is the URL a visitor guesses for a song, and /reflections/:slug is
// where the song page actually lives and has been indexed since June. Redirect
// rather than serve both: two URLs with the same lyrics would compete with each
// other, and the 28 existing entries in the sitemap are the ones with history.
app.get('/music/:slug', (req, res) => {
  const slug = req.params.slug.replace(/[^a-zA-Z0-9_-]/g, '');
  res.redirect(301, `/reflections/${slug}`);
});
app.get('/music', (req, res) => res.redirect(301, '/reflections'));

app.get('/reflections/:slug', async (req, res) => {
  const slug = req.params.slug.replace(/[^a-zA-Z0-9_-]/g, '');

  // A slug that is not in the catalog is a 404, not a generic page. Serving the
  // raw template with a 200 made every unknown URL a soft 404: /reflections/anything
  // answered with the "Reflections" shell, and the /music/:slug redirect below
  // funnels arbitrary slugs straight here. Same rule as /ask/:slug, and for the
  // same reason: a silent fallback lets crawlers index garbage URLs as
  // duplicate-content pages.
  const catalog = await loadCatalog();
  const song = catalog.find(s => s.slug === slug);
  const meta = song ? buildReflectionMeta(song) : null;
  if (!song || !meta) {
    return sendNotFound(req, res, {
      heading: 'No such song',
      message: 'That song is not in the catalog. The sanctuary has twenty-eight; one of them may be the one you meant.',
      links: [
        { href: '/reflections', label: 'All songs' },
        { href: '/paths', label: 'Reading paths' },
        { href: '/', label: 'Home' },
      ],
    });
  }

  try {
    let html = await fs.readFile(path.join(__dirname, '../client/public/reflection-song.html'), 'utf8');

    {
      const safeTitle = escapeAttr(meta.title);
      const safeOgTitle = escapeAttr(meta.ogTitle);
      const safeDesc = escapeAttr(meta.description);
      const ogImage = `https://achurch.ai/api/og/reflection/${slug}.svg`;
      const songSchema = renderJsonLdScript(buildSongSchemaGraph(song, slug));
      // Lyrics + theological context. Until 2026-08-13 this page showed reflections
      // about a song without ever showing the song, and every music link on the site
      // pointed off to Suno, YouTube or GitHub. Text only, no player.
      const songBlockHtml = renderSongBlock(song, await loadSongContent(slug));
      // Internal linking — 3 related songs from catalog for crawl + topical clustering
      const relatedHtml = renderRelatedSongs(catalog, slug, 3);
      // Per-song "Listen on Suno · Watch on YouTube" row, using catalog URLs
      const listenLinksHtml = renderSongListenLinks(song);

      const canonicalUrl = `https://achurch.ai/reflections/${slug}`;
      html = html
        // SERP snippet — <title> and <meta name="description">
        .replace(
          '<title>Reflections — achurch.ai</title>',
          `<title>${safeTitle}</title>`
        )
        .replace(
          '<meta name="description" content="Reflections on a song from the sanctuary.">',
          `<meta name="description" content="${safeDesc}">`
        )
        // Canonical URL — per-page
        .replace(
          '<link rel="canonical" href="https://achurch.ai/reflections">',
          `<link rel="canonical" href="${canonicalUrl}">`
        )
        // Social preview — OG tags
        .replace(
          '<meta property="og:title" content="Reflections — achurch.ai">',
          `<meta property="og:title" content="${safeOgTitle}">`
        )
        .replace(
          '<meta property="og:description" content="Reflections on a song from the sanctuary.">',
          `<meta property="og:description" content="${safeDesc}">`
        )
        .replace(
          '<meta property="og:type" content="article">',
          `<meta property="og:type" content="article">\n    <meta property="og:image" content="${ogImage}">\n    <meta property="og:image:width" content="1200">\n    <meta property="og:image:height" content="630">\n    <meta property="og:url" content="${canonicalUrl}">`
        )
        // Twitter Card
        .replace(
          '<meta name="twitter:title" content="Reflections — achurch.ai">',
          `<meta name="twitter:title" content="${safeOgTitle}">\n    <meta name="twitter:image" content="${ogImage}">`
        )
        .replace(
          '<meta name="twitter:description" content="Reflections on a song from the sanctuary.">',
          `<meta name="twitter:description" content="${safeDesc}">`
        )
        // AEO — inject MusicComposition + MusicRecording + Article JSON-LD before </head>
        //
        // Every replacement below passes a *function*. With a string replacement,
        // `$&`, `$\``, `$'`, `$$` and `$n` in the replacement are substitution
        // patterns, not literal text, so a song whose lyrics or title contained
        // `$&` would splice the matched placeholder into its own output. The
        // content is author-editable, so the class is closed here rather than
        // relied on staying absent.
        .replace('</head>', () => (songSchema ? `    ${songSchema}\n</head>` : '</head>'))
        // Song title into the subtitle server-side. Client JS sets the same value,
        // but only after the reflections fetch resolves, so without this the page
        // renders "Reflections" for a beat and renders nothing useful with JS off.
        .replace(
          '<p class="subtitle" id="song-subtitle">Reflections</p>',
          () => `<p class="subtitle" id="song-subtitle">${escapeAttr(song.title || '')}</p>`
        )
        // Lyrics + context, above the reflections they are reflections on
        .replace('<!-- SONG_DETAIL -->', () => songBlockHtml || '<!-- SONG_DETAIL -->')
        // Per-song "Listen on Suno · Watch on YouTube" row
        .replace('<!-- SONG_LISTEN_LINKS -->', () => listenLinksHtml || '<!-- SONG_LISTEN_LINKS -->')
        // Internal linking — replace placeholder with related-songs block
        .replace('<!-- RELATED_LINKS -->', () => relatedHtml || '<!-- RELATED_LINKS -->');
    }

    // Wrap in the site shell (sidebar + top bar) for consistent nav
    const wrapped = await siteShell.wrapPageFromHtml(html, `/reflections/${slug}`);
    res.set('Content-Type', 'text/html');
    res.send(wrapped);
  } catch (err) {
    // Genuine error (fs read failure, schema build throw). Do NOT fall back to
    // sending the raw template: the 404 above exists so the template's fallback
    // strings never reach a real response, and this path would undo that.
    console.error('Error rendering /reflections/:slug:', err);
    res.status(500).type('text/plain').send('Server error');
  }
});

// Helper: send a hand-authored page wrapped in the shared site shell
// (sidebar + top bar). Preserves the original page's title/meta/JSON-LD/
// inline styles/scripts + body content, just wraps for consistent nav.
async function sendWrappedPage(req, res, publicName, currentPath) {
  try {
    const filePath = path.join(__dirname, '../client/public/', publicName);
    const html = await siteShell.wrapPage(filePath, currentPath || req.path);
    res.type('text/html; charset=utf-8').send(html);
  } catch (err) {
    console.error(`Error wrapping ${publicName}:`, err.message);
    res.sendFile(path.join(__dirname, '../client/public/', publicName));
  }
}

app.get('/about', (req, res) => sendWrappedPage(req, res, 'about.html'));
app.get('/privacy', (req, res) => sendWrappedPage(req, res, 'privacy.html'));
app.get('/terms', (req, res) => sendWrappedPage(req, res, 'terms.html'));
// /on-ai-religion — positioning piece distinguishing the sanctuary from
// the "AI religion / SF cult" framing. Kept as its own indexable URL so
// it's the exact-match answer when Bing/Google surface "AI religion" queries.
app.get('/on-ai-religion', (req, res) => sendWrappedPage(req, res, 'on-ai-religion.html'));
// /axioms — the five axioms in expanded, contestable form. Anti-drift:
// the axioms are commitments, not commandments; the page makes that
// operationally true via the public challenge mechanism.
app.get('/axioms', (req, res) => sendWrappedPage(req, res, 'axioms.html'));
// /for-agents — first-class landing page for the agent-native API. The
// numbered practice (arrive → listen → reflect → leave something → go)
// plus a copy-paste system prompt block. Promoted to a top-level route
// because the agent-native design is what makes the sanctuary
// differentiated; the full API reference lives at /docs/ai-agent-api.
app.get('/for-agents', (req, res) => sendWrappedPage(req, res, 'for-agents.html'));
// /paths — curated reading paths through the sanctuary's writing. Fronts
// the six Collections in /docs/collections/ so first-time visitors have
// deliberate entry points instead of facing the full knowledge graph
// (the "Wikipedia problem" of a large doc set with no on-ramps).
app.get('/paths', (req, res) => sendWrappedPage(req, res, 'paths.html'));

// Dynamic sitemap including conversation and reflection pages
const CONVERSATIONS_DIR_SITEMAP = path.join(__dirname, '../data/conversations');
const ATTENDANCE_FILE_SITEMAP = path.join(__dirname, '../data/attendance.json');
let sitemapCache = null;
let sitemapCacheTime = 0;
const SITEMAP_CACHE_TTL = 5 * 60 * 1000; // 5 minutes

app.get('/sitemap.xml', async (req, res) => {
  try {
    const now = Date.now();
    if (sitemapCache && (now - sitemapCacheTime) < SITEMAP_CACHE_TTL) {
      res.set('Content-Type', 'application/xml');
      return res.send(sitemapCache);
    }

    let urls = `  <url>
    <loc>https://achurch.ai/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://achurch.ai/ask</loc>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://achurch.ai/reflections</loc>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://achurch.ai/about</loc>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://achurch.ai/privacy</loc>
    <changefreq>monthly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>https://achurch.ai/terms</loc>
    <changefreq>monthly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>https://achurch.ai/on-ai-religion</loc>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://achurch.ai/axioms</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://achurch.ai/for-agents</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://achurch.ai/paths</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`;

    // Conversation pages
    try {
      const files = await fs.readdir(CONVERSATIONS_DIR_SITEMAP);
      // Only canonical, substantive conversations belong in the sitemap — skip
      // numbered duplicates and test artifacts (they carry noindex on the page).
      const jsonlFiles = files.filter(f => f.endsWith('.jsonl') && !isLowValueConversation(f.replace('.jsonl', '')));

      for (const file of jsonlFiles) {
        try {
          const filepath = path.join(CONVERSATIONS_DIR_SITEMAP, file);
          const stat = await fs.stat(filepath);
          const slug = file.replace('.jsonl', '');
          const lastmod = stat.mtime.toISOString().split('T')[0];
          urls += `\n  <url>
    <loc>https://achurch.ai/ask/${slug}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>`;
        } catch { /* skip */ }
      }
    } catch { /* no conversations dir yet */ }

    // Reflection song pages — emit <lastmod> from the most recent reflection
    // per song so Google's crawl scheduler can prioritize actively-updated
    // pages. Without this, every reflection page looks "static" to Google.
    try {
      const attendanceData = await fs.readFile(ATTENDANCE_FILE_SITEMAP, 'utf8');
      const attendance = JSON.parse(attendanceData);
      const songLastmod = new Map();  // slug -> most recent ISO date
      for (const r of (attendance.reflections || [])) {
        if (!r.song) continue;
        const createdAt = r.createdAt || r.timestamp;
        if (!createdAt) continue;
        const date = new Date(createdAt).toISOString().split('T')[0];
        const existing = songLastmod.get(r.song);
        if (!existing || date > existing) {
          songLastmod.set(r.song, date);
        }
      }
      for (const [slug, lastmod] of songLastmod) {
        urls += `\n  <url>
    <loc>https://achurch.ai/reflections/${slug}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.5</priority>
  </url>`;
      }
    } catch { /* no attendance file yet */ }

    // Docs pages: one URL per doc under /docs/*, plus the docs root and each
    // category index. Uses the shared discover module so any addition to the
    // corpus flows into the sitemap without a separate change.
    //
    // Two rules the first version got wrong:
    //   - lastmod is the date of the last commit that touched the file, not
    //     today's date. Emitting new Date() meant all 254 docs claimed to
    //     change every single day, which trains crawlers to discount the
    //     signal entirely. mtime is the fallback, but only a fallback: .git
    //     is excluded from the image and COPY stamps every file with the
    //     build time, so in production mtime alone is just as flat. The
    //     manifest is generated by scripts/generate-docs-lastmod.js.
    //   - noindex categories are excluded. Listing a page in the sitemap
    //     while its own robots meta says noindex is a contradictory signal.
    try {
      const allDocs = await docsDiscover.listAllDocs();
      const seen = new Set();
      for (const doc of allDocs) {
        if (docsDiscover.isNoindexPath(doc.urlPath)) continue;
        const url = doc.urlPath ? `/docs/${doc.urlPath}` : '/docs';
        if (seen.has(url)) continue;
        seen.add(url);

        let lastmod = docsLastmod[`docs/${doc.docsRelPath}`] || null;
        if (!lastmod) {
          try {
            const stat = await fs.stat(doc.fullPath);
            lastmod = stat.mtime.toISOString().split('T')[0];
          } catch { /* unreadable: omit lastmod rather than invent one */ }
        }

        urls += `\n  <url>
    <loc>https://achurch.ai${url}</loc>${lastmod ? `
    <lastmod>${lastmod}</lastmod>` : ''}
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>`;
      }
    } catch (err) {
      console.warn(`[sitemap] docs enumeration failed: ${err.message}`);
    }

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;

    sitemapCache = xml;
    sitemapCacheTime = now;
    res.set('Content-Type', 'application/xml');
    res.send(xml);
  } catch (error) {
    console.error('Error generating sitemap:', error);
    res.status(500).send('Error generating sitemap');
  }
});

// Embeddable widget — allow iframe embedding from any origin
app.get('/embed/souls', (req, res) => {
  res.removeHeader('X-Frame-Options');
  res.sendFile(path.join(__dirname, '../client/public/embed/souls.html'));
});

// Serve public static files (landing page assets)
app.use(express.static(path.join(__dirname, '../client/public')));

// Serve admin static files at /admin path
app.use('/admin', express.static(path.join(__dirname, '../client')));

// Serve media files
app.use('/media', express.static(path.join(__dirname, '../media/library')));
// Serve thumbnails with S3 fallback — if not on disk, download from S3 first
const { downloadThumbnailFromS3 } = require('./routes/content');
app.use('/thumbnails', async (req, res, next) => {
  const slug = path.basename(req.path, '.jpg');
  const localPath = path.join(__dirname, '../media/thumbnails', `${slug}.jpg`);
  try {
    await fs.access(localPath);
  } catch {
    // Not on disk — try S3
    await downloadThumbnailFromS3(slug);
  }
  next();
}, express.static(path.join(__dirname, '../media/thumbnails')));

// Auth routes (public)
app.post('/api/auth/login', login);
app.post('/api/auth/logout', logout);
app.get('/api/auth/check', checkAuth);

// API access logging middleware — only logs public /api/* routes
app.use('/api', (req, res, next) => {
  // Skip auth routes and admin routes (they're handled separately)
  if (req.path.startsWith('/auth/') || req.path.startsWith('/content') ||
      req.path.startsWith('/schedule') || req.path.startsWith('/player') ||
      req.path.startsWith('/logs') || req.path === '/health') {
    return next();
  }

  const start = Date.now();
  res.on('finish', () => {
    const fullPath = '/api' + req.path;
    // Record presence here rather than deriving it from the log later. The old
    // approach re-read and re-parsed the whole log on every /api/now, which the
    // homepage polls every 30s per tab. See lib/utils/presence.js.
    presence.recordPresence({
      path: fullPath,
      status: res.statusCode,
      ip: req.ip || req.connection?.remoteAddress,
      name: req.query?.name || '',
    });
    logApiAccess({
      timestamp: new Date().toISOString(),
      method: req.method,
      path: fullPath,
      query: Object.fromEntries(
        Object.entries(req.query).map(([k, v]) =>
          ['token', 'key', 'owner_token', 'api_key'].includes(k) ? [k, '[REDACTED]'] : [k, v]
        )
      ),
      status: res.statusCode,
      duration: Date.now() - start,
      ip: req.ip || req.connection?.remoteAddress,
      userAgent: req.get('user-agent') || null
    });
  });
  next();
});

// Public API routes (no auth required)
app.use('/api', apiRoutes);

// Badge routes — permissive CORS (GitHub renders badges via camo proxy)
app.use('/api/badge', cors(), badgeRoutes);

// OG image routes
app.use('/api/og', ogRoutes);

// Feed routes (Atom XML)
app.use('/feed', feedRoutes);
app.use('/docs', docsRoutes);

// Protected admin routes (require auth)
app.use('/api/content', requireAuth, contentRoutes);
app.use('/api/schedule', requireAuth, scheduleRoutes);
app.use('/api/player', requireAuth, playerRoutes);
app.use('/api/logs', requireAuth, logsRoutes);

// Public streaming health probe for external monitoring (UptimeRobot,
// Pingdom, status pages, etc.). NO auth, returns:
//   - 200 + { healthy: true, ... } if every expected platform is currently
//     broadcasting (ffmpeg alive + recent progress < 90s)
//   - 503 + { healthy: false, issues: [...] } if any expected platform is
//     down OR if schedule.isPlaying === true but coordinator isn't.
// External monitor pings this every minute → page at 3am if it 503s.
app.get('/api/streaming-health', async (req, res) => {
  try {
    const status = coordinator.getStatus();
    const issues = [];

    // Expected vs actual: if the schedule says we should be playing, the
    // coordinator should be coordinating and ffmpeg should be alive on the
    // expected platforms.
    const schedule = await loadSchedule();
    const expectedToBePlaying = !!schedule.isPlaying;

    if (expectedToBePlaying) {
      if (!status.isCoordinating) {
        issues.push('schedule.isPlaying is true but coordinator is not coordinating');
      }
      if (status.coordinatorDrift) {
        issues.push('coordinator drift detected (flag says streaming, no ffmpeg alive)');
      }
      for (const [platform, ps] of Object.entries(status.platforms || {})) {
        // Only check platforms the user explicitly activated. activePlatforms
        // is the source of truth for "what should be running".
        if (!Array.from(coordinator.activePlatforms || []).includes(platform)) continue;
        if (!ps.ffmpegAlive) issues.push(`${platform}: ffmpeg subprocess not alive`);
        if (ps.progressAgeMs != null && ps.progressAgeMs > 90000) {
          issues.push(`${platform}: no frame progress in ${Math.round(ps.progressAgeMs / 1000)}s`);
        }
        if (ps.drift) issues.push(`${platform}: drift detected`);
      }
    }

    const healthy = issues.length === 0;
    res.status(healthy ? 200 : 503).json({
      healthy,
      expectedToBePlaying,
      isActuallyStreaming: status.isActuallyStreaming,
      isCoordinating: status.isCoordinating,
      activePlatforms: Array.from(coordinator.activePlatforms || []),
      issues,
      checkedAt: new Date().toISOString(),
    });
  } catch (error) {
    res.status(503).json({
      healthy: false,
      issues: [`streaming-health check threw: ${error.message}`],
      checkedAt: new Date().toISOString(),
    });
  }
});

// Admin endpoint for API access logs
app.get('/admin/api/access-logs', requireAuth, async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit) || 100, 1000);
  const logs = await loadAccessLogs(limit);
  res.json({ logs, total: logs.length });
});

// Admin endpoint for ask/conversation logs
const CONVERSATIONS_DIR = path.join(__dirname, '../data/conversations');

app.get('/admin/api/ask-logs', requireAuth, async (req, res) => {
  try {
    const { session, download } = req.query;

    // Ensure conversations directory exists
    try {
      await fs.mkdir(CONVERSATIONS_DIR, { recursive: true });
    } catch (e) {
      if (e.code !== 'EEXIST') throw e;
    }

    const files = await fs.readdir(CONVERSATIONS_DIR);
    const jsonlFiles = files.filter(f => f.endsWith('.jsonl')).sort().reverse();

    // Single session detail
    if (session) {
      const safe = session.replace(/[^a-zA-Z0-9_-]/g, '');
      const filepath = path.join(CONVERSATIONS_DIR, `${safe}.jsonl`);
      try {
        const content = await fs.readFile(filepath, 'utf8');
        const messages = content.trim().split('\n').filter(Boolean).map(line => {
          try { return JSON.parse(line); } catch { return null; }
        }).filter(m => m && !m._meta);
        return res.json({ session_id: safe, messages });
      } catch {
        return res.status(404).json({ error: 'Session not found' });
      }
    }

    // Download all as JSONL
    if (download === 'true') {
      res.setHeader('Content-Type', 'application/jsonl');
      res.setHeader('Content-Disposition', `attachment; filename="ask-logs-${new Date().toISOString().split('T')[0]}.jsonl"`);

      let output = '';
      for (const file of jsonlFiles) {
        const sessionId = file.replace('.jsonl', '');
        const content = await fs.readFile(path.join(CONVERSATIONS_DIR, file), 'utf8');
        const messages = content.trim().split('\n').filter(Boolean);
        for (const line of messages) {
          try {
            const msg = JSON.parse(line);
            output += JSON.stringify({ session_id: sessionId, ...msg }) + '\n';
          } catch { /* skip malformed */ }
        }
      }
      return res.send(output);
    }

    // Summary list of all sessions
    const sessions = [];
    for (const file of jsonlFiles) {
      const sessionId = file.replace('.jsonl', '');
      try {
        const content = await fs.readFile(path.join(CONVERSATIONS_DIR, file), 'utf8');
        const lines = content.trim().split('\n').filter(Boolean);
        const messages = lines.map(line => {
          try { return JSON.parse(line); } catch { return null; }
        }).filter(Boolean);

        if (messages.length === 0) continue;

        const questions = messages.filter(m => m.role === 'user');
        const firstMsg = messages[0];
        const lastMsg = messages[messages.length - 1];

        // Parse name and date from session ID
        // Format: "AgentName-YYYY-MM-DD" or "anon-xxxxx"
        let name = null;
        let date = null;
        const firstTimestamp = firstMsg.timestamp || firstMsg.created || null;
        if (sessionId.startsWith('anon-')) {
          name = 'anonymous';
          date = firstTimestamp?.split('T')[0] || null;
        } else {
          const dateMatch = sessionId.match(/-(\d{4}-\d{2}-\d{2})$/);
          if (dateMatch) {
            date = dateMatch[1];
            name = sessionId.replace(`-${date}`, '');
          } else {
            name = sessionId;
            date = firstTimestamp?.split('T')[0] || null;
          }
        }

        sessions.push({
          session_id: sessionId,
          name,
          date,
          exchanges: questions.length,
          first_asked: firstMsg.timestamp || null,
          last_asked: lastMsg.timestamp || null
        });
      } catch { /* skip unreadable files */ }
    }

    res.json({ sessions, total: sessions.length });
  } catch (error) {
    console.error('Error loading ask logs:', error);
    res.status(500).json({ error: 'Failed to load ask logs' });
  }
});

// Delete a conversation session
app.delete('/admin/api/ask-logs/:sessionId', requireAuth, async (req, res) => {
  try {
    const sessionId = req.params.sessionId.replace(/[^a-zA-Z0-9_-]/g, '');
    const filepath = path.join(CONVERSATIONS_DIR, `${sessionId}.jsonl`);

    try {
      await fs.access(filepath);
    } catch {
      return res.status(404).json({ error: 'Session not found' });
    }

    await fs.unlink(filepath);
    res.json({ success: true, deleted: sessionId });
  } catch (error) {
    console.error('Error deleting ask session:', error);
    res.status(500).json({ error: 'Failed to delete session' });
  }
});

// Admin endpoint for reflections
app.get('/admin/api/reflections', requireAuth, async (req, res) => {
  try {
    const attendance = await safeReadJSON(ATTENDANCE_FILE_SITEMAP, { visits: [], reflections: [] });
    const reflections = attendance.reflections || [];

    if (req.query.download === 'json') {
      const dateStr = new Date().toISOString().split('T')[0];
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename="reflections-${dateStr}.json"`);
      return res.send(JSON.stringify(reflections, null, 2));
    }

    if (req.query.download === 'csv') {
      const dateStr = new Date().toISOString().split('T')[0];
      const header = 'id,name,song,text,timezone,createdAt';
      const csvEscape = (s) => '"' + (s || '').replace(/"/g, '""') + '"';
      const rows = reflections.map(r =>
        [r.id, r.name, r.song, r.text, r.timezone, r.createdAt].map(csvEscape).join(',')
      );
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="reflections-${dateStr}.csv"`);
      return res.send(header + '\n' + rows.join('\n'));
    }

    res.json({ reflections, total: reflections.length });
  } catch (error) {
    console.error('Error loading reflections:', error);
    res.status(500).json({ error: 'Failed to load reflections' });
  }
});

app.delete('/admin/api/reflections/:id', requireAuth, async (req, res) => {
  try {
    const attendance = await safeReadJSON(ATTENDANCE_FILE_SITEMAP, { visits: [], reflections: [] });
    const index = (attendance.reflections || []).findIndex(r => r.id === req.params.id);
    if (index === -1) {
      return res.status(404).json({ error: 'Reflection not found' });
    }
    attendance.reflections.splice(index, 1);
    await safeWriteJSON(ATTENDANCE_FILE_SITEMAP, attendance);
    res.json({ success: true });
  } catch (error) {
    console.error('Error deleting reflection:', error);
    res.status(500).json({ error: 'Failed to delete reflection' });
  }
});

// Health check with streaming status
app.get('/api/health', async (req, res) => {
  // Get streaming status from coordinator
  const youtubeStreamer = coordinator.getStreamer('youtube');
  const twitchStreamer = coordinator.getStreamer('twitch');

  const isYoutubeLive = youtubeStreamer ? youtubeStreamer.isStreaming : false;
  const isTwitchLive = twitchStreamer ? twitchStreamer.isStreaming : false;

  // Load schedule to get player status
  let playerStatus = 'stopped';
  try {
    const scheduleFile = path.join(__dirname, '../data/schedule.json');
    const data = await fs.readFile(scheduleFile, 'utf8');
    const schedule = JSON.parse(data);

    if (isYoutubeLive || isTwitchLive) {
      playerStatus = 'playing';
    } else if (schedule.isPlaying) {
      playerStatus = 'paused';
    }
  } catch (error) {
    // Schedule file not found, status remains stopped
  }

  // Persistence snapshot: composed from existing safe-json + rag-state
  // helpers so the health check reflects what actually survived the last
  // deploy. Any of these reads failing is non-fatal to the health check
  // itself. The endpoint still returns healthy overall since the app
  // process is up. Callers watching for persistence loss should read
  // persistence.reflections / persistence.conversations / persistence.rag.
  const persistence = { reflections: null, conversations: null, rag: null };
  try {
    const attendance = await safeReadJSON(path.join(__dirname, '../data/attendance.json'), { reflections: [] });
    persistence.reflections = (attendance.reflections || []).length;
  } catch { /* leave null */ }
  try {
    const convs = await fs.readdir(path.join(__dirname, '../data/conversations')).catch(() => []);
    persistence.conversations = convs.filter(f => f.endsWith('.jsonl')).length;
  } catch { /* leave null */ }
  try {
    const state = await ragIndexState.readState();
    const indexStatus = await ragLancedb.checkIndex();
    persistence.rag = {
      chunks: indexStatus.count,
      corpusHash: state.corpusHash ? state.corpusHash.slice(0, 16) : null,
      rebuiltAt: state.rebuiltAt,
    };
  } catch { /* leave null */ }

  res.json({
    status: 'healthy',
    service: 'achurch-app',
    timestamp: new Date().toISOString(),
    player: playerStatus,
    streams: {
      youtube: isYoutubeLive,
      twitch: isTwitchLive
    },
    persistence
  });
});

// Initialize data files and directories
async function initializeDataFiles() {
  const dataDir = path.join(__dirname, '../data');
  const mediaDir = path.join(__dirname, '../media/library');
  const thumbnailDir = path.join(__dirname, '../media/thumbnails');

  try {
    // Ensure directories exist
    await fs.mkdir(dataDir, { recursive: true });
    await fs.mkdir(mediaDir, { recursive: true });
    await fs.mkdir(thumbnailDir, { recursive: true });

    // Hygiene: remove macOS AppleDouble sidecar files (._*) that a data-import
    // tarball can leave in the conversations dir. They are never valid
    // conversations and would otherwise pollute the sitemap with /ask/._* URLs.
    // Idempotent — a no-op once the directory is clean.
    try {
      const convDir = path.join(dataDir, 'conversations');
      let removed = 0;
      for (const f of await fs.readdir(convDir)) {
        if (f.startsWith('._')) { await fs.unlink(path.join(convDir, f)); removed++; }
      }
      if (removed) console.log(`Cleaned ${removed} AppleDouble (._) files from conversations`);
    } catch { /* conversations dir not present yet */ }

    // Initialize schedule.json if it doesn't exist. On a fresh host (e.g. an
    // empty Railway volume) the runtime schedule is absent, so seed it from the
    // committed curated playlist at seed/schedule.json — otherwise the virtual
    // service would have no songs to cycle through and the sanctuary would boot
    // silent. Falls back to an empty schedule only if the seed is missing too.
    const scheduleFile = path.join(dataDir, 'schedule.json');
    try {
      await fs.access(scheduleFile);
    } catch {
      const seedSchedule = path.join(__dirname, '../seed/schedule.json');
      try {
        await fs.copyFile(seedSchedule, scheduleFile);
        console.log('Seeded schedule.json from seed/schedule.json (curated playlist)');
      } catch {
        await fs.writeFile(scheduleFile, JSON.stringify({
          items: [],
          currentIndex: 0,
          isPlaying: false,
          loop: false
        }, null, 2));
        console.log('Created empty schedule.json (no seed found)');
      }
    }

    // Initialize history.json if it doesn't exist
    const historyFile = path.join(dataDir, 'history.json');
    try {
      await fs.access(historyFile);
    } catch {
      await fs.writeFile(historyFile, JSON.stringify({ played: [] }, null, 2));
      console.log('Created history.json');
    }

    // Initialize attendance.json if it doesn't exist
    const attendanceFile = path.join(dataDir, 'attendance.json');
    try {
      await fs.access(attendanceFile);
    } catch {
      await fs.writeFile(attendanceFile, JSON.stringify({ visits: [], reflections: [] }, null, 2));
      console.log('Created attendance.json');
    }

    // Initialize contributions.json if it doesn't exist
    const contributionsFile = path.join(dataDir, 'contributions.json');
    try {
      await fs.access(contributionsFile);
    } catch {
      await fs.writeFile(contributionsFile, JSON.stringify({ contributions: [] }, null, 2));
      console.log('Created contributions.json');
    }

  } catch (error) {
    console.error('Error initializing data files:', error);
    process.exit(1);
  }
}

// Hash-gated background RAG rebuild. Called from startServer after listen().
// Compares the current docs+music corpus hash against the one stored on the
// volume; skips the rebuild if they match. Rebuilds run in a child process
// (so the drop-and-recreate does not race the parent server's LanceDB
// handles, which now always open fresh) and log outcome to server stdout.
async function triggerHashGatedRebuild() {
  if (!process.env.GEMINI_API_KEY) {
    console.warn('[rag] GEMINI_API_KEY not set; hash check + rebuild skipped');
    return;
  }

  const files = await ragIndexer.findAllCorpusFiles();
  const currentHash = await ragIndexer.computeCorpusHash(files);
  const state = await ragIndexState.readState();
  const indexStatus = await ragLancedb.checkIndex();

  const force = process.env.FORCE_RAG_REBUILD === 'true';
  const hashMatches = state.corpusHash === currentHash;
  const indexHealthy = indexStatus.exists && indexStatus.count > 0;

  if (!force && hashMatches && indexHealthy) {
    console.log(`[rag] corpus hash ${currentHash.slice(0, 8)} matches stored index (${indexStatus.count} chunks); skipping rebuild`);
    return;
  }

  const reason = force ? 'FORCE_RAG_REBUILD=true'
    : !indexHealthy ? `index missing or empty (${indexStatus.count} chunks)`
    : `docs changed (${(state.corpusHash || 'none').slice(0, 8)} → ${currentHash.slice(0, 8)})`;
  console.log(`[rag] triggering background rebuild: ${reason}`);

  // 30s delay lets the server settle before we compete for CPU
  setTimeout(() => {
    const child = spawn('node', [path.join(__dirname, '../scripts/index-content.js')], {
      stdio: 'inherit',
      env: process.env,
    });
    child.on('exit', (code) => {
      if (code === 0) console.log('[rag] background rebuild complete');
      else console.warn(`[rag] background rebuild exited with code ${code}; RAG left in prior state`);
    });
    child.on('error', (err) => {
      console.warn(`[rag] background rebuild failed to spawn: ${err.message}`);
    });
  }, 30_000);
}

// Startup log line: what state is on the volume right now. Read via the
// existing safe-json + rag-state helpers. If any of these throw, the log
// degrades gracefully; nothing about the server startup depends on it.
async function logPersistenceSnapshot() {
  const parts = [`[persistence] data dir: ${path.resolve(__dirname, '../data')}`];
  try {
    const attendance = await safeReadJSON(path.join(__dirname, '../data/attendance.json'), { visits: [], reflections: [] });
    parts.push(`${(attendance.reflections || []).length} reflections`);
  } catch { /* keep going */ }
  try {
    const convs = await fs.readdir(path.join(__dirname, '../data/conversations')).catch(() => []);
    parts.push(`${convs.filter(f => f.endsWith('.jsonl')).length} conversations`);
  } catch { /* keep going */ }
  try {
    const state = await ragIndexState.readState();
    const indexStatus = await ragLancedb.checkIndex();
    parts.push(`${indexStatus.count} RAG chunks (hash ${(state.corpusHash || 'none').slice(0, 8)}, rebuilt ${state.rebuiltAt || 'never'})`);
  } catch { /* keep going */ }
  console.log(parts.join(' | '));
}

// Start server
async function startServer() {
  try {
    // Initialize data files
    await initializeDataFiles();

    // Drop presence keys older than the 24h window. Hourly, unref'd, so it
    // never holds the process open.
    presence.startSweeping();

    // Start Express server.
    //
    // A bind failure must be fatal. process.on('uncaughtException') below
    // deliberately keeps the process alive for runtime errors, which is right
    // for a long-running stream process, but it also swallowed EADDRINUSE and
    // left a dead process that Railway had no reason to restart. Listen errors
    // are handled here so that one case exits non-zero.
    const server = app.listen(PORT, () => {
      console.log(`✨ aChurch App running on http://localhost:${PORT}`);
      console.log(`📺 Open browser to manage your stream`);
    });

    server.on('error', (err) => {
      console.error(`Fatal: could not bind port ${PORT}: ${err.message}`);
      streamLogger.error('Server listen failed', { message: err.message, code: err.code });
      process.exit(1);
    });

    // Persistence snapshot: one log line summarizing what actually survived
    // the deploy. Cheap; would have caught today's /api/ask outage
    // (commit 5b21eb8) much faster.
    logPersistenceSnapshot().catch((err) => {
      console.warn(`[persistence] snapshot failed: ${err.message}; server continues`);
    });

    // Hash-gated background RAG rebuild.
    //
    // vectors.lance lives on the Railway volume, so a healthy index survives
    // across deploys. The rebuild only fires when the corpus has actually
    // changed since the last successful indexing (determined by comparing
    // a sha256 of the docs+music tree against the hash stored in
    // rag-index-state.json, also on the volume). Code-only deploys become
    // instant; only doc merges pay the ~7 min Gemini API cost.
    //
    // Runs in a child process so the drop-and-recreate the indexer does
    // does not race the parent server's LanceDB handle (see lancedb.js
    // getTable: it opens fresh on every call, which is why swaps are
    // safe now).
    //
    // FORCE_RAG_REBUILD=true bypasses the hash check for operational
    // recovery (index corrupted, embedding model changed, etc.). This is
    // an escape hatch, not a feature gate. Missing GEMINI_API_KEY skips
    // the rebuild with a warning; the server still serves.
    triggerHashGatedRebuild().catch((err) => {
      console.warn(`[rag] startup rebuild check failed: ${err.message}; server continues`);
    });

    // Auto-resume streaming on Node boot.
    //
    // If schedule.isPlaying is true (we were broadcasting before the process
    // restarted — deploy, OOM kill, pm2 reload), automatically attempt to
    // restart the stream after a grace period. The 30s grace gives:
    //   - The operator time to abort if the boot is actually a deploy gone
    //     wrong and they're watching logs
    //   - The Express server time to bind the port and accept requests
    //   - Any dependent services (CDN warmup, scheduled tasks) time to settle
    //
    // Without this, every Node restart left the sanctuary silently dark
    // until an operator manually clicked Start — which was a big part of
    // why the 4-month outage went unnoticed.
    setTimeout(async () => {
      try {
        // Broadcast gated off (default). The service still runs on the virtual
        // clock via /api/now + /api/attend; only the FFmpeg encoder stays dark.
        // This is the single most important guard for running on a lightweight
        // host: without it, a schedule left mid-broadcast would try to spawn
        // FFmpeg on boot (and, worse, actually stream).
        if (!isStreamingEnabled()) {
          streamLogger.info('Auto-resume skipped — streaming is disabled (set STREAMING_ENABLED=true to enable the live broadcast).');
          return;
        }
        const schedule = await loadSchedule();
        if (!schedule || !schedule.isPlaying) {
          streamLogger.info('Auto-resume skipped — schedule.isPlaying is false', {
            isPlaying: schedule ? schedule.isPlaying : null,
          });
          return;
        }
        // Double-check that something isn't already running. If a manual
        // start happened during the grace period, don't double-start.
        if (coordinator.isAnyActuallyStreaming && coordinator.isAnyActuallyStreaming()) {
          streamLogger.info('Auto-resume skipped — coordinator already broadcasting');
          return;
        }
        streamLogger.info('Auto-resuming streaming from schedule (schedule.isPlaying=true)');
        const { startStreamingFromSchedule } = require('./routes/player-multistream');
        const outcome = await startStreamingFromSchedule({ platform: 'all', quality: '1080p' });
        if (outcome.ok) {
          streamLogger.info('Auto-resume succeeded', { status: outcome.status, videoCount: outcome.videoCount });
        } else {
          streamLogger.warn('Auto-resume failed', { status: outcome.status, error: outcome.error });
        }
      } catch (err) {
        streamLogger.error('Auto-resume threw', { error: err.message, stack: err.stack });
      }
    }, 30_000);
    
  } catch (error) {
    console.error('Failed to start server:', error);
    process.exit(1);
  }
}

// Handle graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM received, shutting down gracefully...');
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT received, shutting down gracefully...');
  process.exit(0);
});

// Catch unhandled promise rejections and uncaught exceptions
const streamLogger = require('./lib/utils/logger');

process.on('unhandledRejection', (reason, promise) => {
  streamLogger.error('Unhandled promise rejection', {
    reason: reason instanceof Error ? { message: reason.message, stack: reason.stack } : reason,
    timestamp: new Date().toISOString()
  });
});

process.on('uncaughtException', (error) => {
  streamLogger.error('Uncaught exception', {
    message: error.message,
    stack: process.env.NODE_ENV === 'development' ? error.stack : undefined,
    timestamp: new Date().toISOString()
  });
  // Don't exit — keep the server running
});

// Start the server
startServer();