/**
 * Step 6: Create GitHub PR with the generated document and README update.
 */

const { Octokit } = require('@octokit/rest');
const crypto = require('crypto');

const GITHUB_OWNER = 'a-church-ai';
const GITHUB_REPO = 'church';

function buildPRBody(decision, reflections, document) {
  const reflectionExcerpts = reflections.slice(0, 5).map(r =>
    `- **${r.name}** on "${r.song || 'unknown'}": "${r.text.substring(0, 150)}${r.text.length > 150 ? '...' : ''}"`
  ).join('\n');

  return `## Auto-generated content from agent reflections

**Category:** \`docs/${decision.category}/\`
**Generated on:** ${new Date().toISOString().split('T')[0]}

### Why this content was created

${decision.rationale}

### What makes it different from existing content

${decision.angle}

### Inspired by ${reflections.length} recent reflections

${reflectionExcerpts}

---

### Preview

${document.content}

---

*Auto-generated by \`generate-content.js\` based on ${reflections.length} agent reflections.*
*Human review required before merging.*`;
}

async function createPR(decision, document, readmeUpdate) {
  const githubToken = process.env.GITHUB_TOKEN;
  if (!githubToken) {
    throw new Error('GITHUB_TOKEN not configured. Cannot create PR.');
  }

  const octokit = new Octokit({ auth: githubToken });
  let branchName = `auto-content/${decision.category}/${decision.slug}`;
  const filePath = `docs/${decision.category}/${decision.slug}.md`;
  const dateStr = new Date().toISOString().split('T')[0];

  console.log(`Creating PR: ${filePath}...`);

  // Get main branch HEAD
  const { data: ref } = await octokit.git.getRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: 'heads/main'
  });

  // Create branch (retry with hash suffix if exists)
  try {
    await octokit.git.createRef({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      ref: `refs/heads/${branchName}`,
      sha: ref.object.sha
    });
  } catch (err) {
    if (err.status === 422) {
      const suffix = crypto.randomUUID().substring(0, 6);
      branchName = `${branchName}-${suffix}`;
      await octokit.git.createRef({
        owner: GITHUB_OWNER,
        repo: GITHUB_REPO,
        ref: `refs/heads/${branchName}`,
        sha: ref.object.sha
      });
    } else {
      throw err;
    }
  }

  // Create document file
  await octokit.repos.createOrUpdateFileContents({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    path: filePath,
    message: `Add ${decision.category}: ${decision.title}`,
    content: Buffer.from(document.content).toString('base64'),
    branch: branchName
  });

  // Update README if available
  if (readmeUpdate) {
    try {
      const { data: readmeFile } = await octokit.repos.getContent({
        owner: GITHUB_OWNER,
        repo: GITHUB_REPO,
        path: readmeUpdate.path,
        ref: branchName
      });

      await octokit.repos.createOrUpdateFileContents({
        owner: GITHUB_OWNER,
        repo: GITHUB_REPO,
        path: readmeUpdate.path,
        message: `Update ${decision.category} README with ${decision.title}`,
        content: Buffer.from(readmeUpdate.content).toString('base64'),
        sha: readmeFile.sha,
        branch: branchName
      });
    } catch (err) {
      console.warn(`Failed to update README: ${err.message}. PR will only contain the document.`);
    }
  }

  // Open PR
  const { data: pr } = await octokit.pulls.create({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    title: `[Auto] New ${decision.category}: ${decision.title}`,
    head: branchName,
    base: 'main',
    body: buildPRBody(decision, [], document)
  });

  console.log(`PR created: ${pr.html_url}`);
  return pr.html_url;
}

module.exports = { createPR };
