const fs = require('fs').promises;
const path = require('path');
const { isWithdrawn, isIndexable } = require('./conversation-quality');
const { safeReadJSON } = require('./safe-json');
const presence = require('./presence');

// Data file paths
const SCHEDULE_FILE = path.join(__dirname, '../../../data/schedule.json');
const CATALOG_FILE = path.join(__dirname, '../../../../music/library.json');
const COMPANIONS_FILE = path.join(__dirname, '../../../../music/companions.json');
const MUSIC_DIR = path.join(__dirname, '../../../../music');
// Files the API writes on every visit. DATA_DIR points them elsewhere so tests
// write to a scratch directory; production leaves it unset. Until 2026-09-28
// the tests set DATA_DIR but nothing read it, and every run appended visits
// to the real app/data/attendance.json.
const RUNTIME_DIR = process.env.DATA_DIR || path.join(__dirname, '../../../data');
const ATTENDANCE_FILE = path.join(RUNTIME_DIR, 'attendance.json');
// One file per date of the services planned for it (lib/service/plans.js).
const SERVICES_DIR = path.join(RUNTIME_DIR, 'services');
const ACCESS_LOG_FILE = path.join(RUNTIME_DIR, 'api-access.jsonl');
// The souls present in the last 24 hours, kept so a deploy does not reset the
// count (lib/utils/presence.js).
const PRESENCE_FILE = path.join(RUNTIME_DIR, 'presence.json');
const CONVERSATIONS_DIR = path.join(__dirname, '../../../data/conversations');

// Time constants
const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000;
const FORTY_EIGHT_HOURS = 48 * 60 * 60 * 1000;

async function loadSchedule() {
  return safeReadJSON(SCHEDULE_FILE, { items: [], currentIndex: 0, isPlaying: false, loop: false });
}

async function loadCatalog() {
  return safeReadJSON(CATALOG_FILE, []);
}

// Each song's ranked companion shortlist, generated by
// app/scripts/generate-companions.js and committed beside library.json.
async function loadCompanions() {
  return safeReadJSON(COMPANIONS_FILE, { songs: {} });
}

// Reflections hidden as spam (hidden-reflections.json). Filtered here, where
// every reader loads attendance, so a hidden reflection is gone from the whole
// site; the reflect write path reads the file directly and keeps the record.
const HIDDEN_REFLECTIONS = new Set(require('./hidden-reflections.json').hidden.map(h => h.id));

const isHiddenReflection = r => HIDDEN_REFLECTIONS.has(r && r.id);

async function loadAttendance() {
  const attendance = await safeReadJSON(ATTENDANCE_FILE, { visits: [], reflections: [] });
  if (Array.isArray(attendance.reflections)) {
    attendance.reflections = attendance.reflections.filter(r => !isHiddenReflection(r));
  }
  return attendance;
}

// Count unique souls: a unique (IP + name) pair over the last 24 hours.
//
// Delegates to lib/utils/presence.js, which records presence as requests happen
// and answers from memory. This used to read the whole access log and parse
// every line on demand, which cost ~85ms per call against a log at the 10MB
// rotation ceiling, on an endpoint the homepage polls every 30 seconds per tab.
// See presence.js for the trade that replaced it and why not to undo it.
async function countSoulsPresent() {
  return presence.countSoulsPresent();
}

// Get recent reflections (last 48 hours)
async function getRecentReflections() {
  const attendance = await loadAttendance();
  const now = Date.now();
  return (attendance.reflections || [])
    .filter(r => (now - new Date(r.createdAt).getTime()) < FORTY_EIGHT_HOURS);
}

// Load a conversation from its JSONL file
async function loadConversation(slug) {
  const safe = slug.replace(/[^a-zA-Z0-9_-]/g, '');
  if (isWithdrawn(safe)) return null;
  const filepath = path.join(CONVERSATIONS_DIR, `${safe}.jsonl`);
  try {
    const content = await fs.readFile(filepath, 'utf8');
    const lines = content.trim().split('\n').filter(Boolean);
    return lines.map(l => { try { return JSON.parse(l); } catch { return null; } }).filter(m => m && !m._meta);
  } catch {
    return null;
  }
}

// Every conversation, most recently active first. Reading and parsing every
// conversation file is the cost here, and every conversation page, the
// archive and the feeds ask for it, so the full list is held for a minute
// (the same window /api/ask/recent caches for). A new question appears
// within that minute.
const CONVERSATION_LIST_TTL = 60 * 1000;
let conversationList = null;
let conversationListTime = 0;

async function listRecentConversations(limit = 20) {
  if (!conversationList || Date.now() - conversationListTime > CONVERSATION_LIST_TTL) {
    conversationList = await readConversationList();
    conversationListTime = Date.now();
  }
  return conversationList.slice(0, limit);
}

async function readConversationList() {
  try {
    const files = await fs.readdir(CONVERSATIONS_DIR);
    const jsonlFiles = files.filter(f => f.endsWith('.jsonl'));

    const conversations = [];
    for (const file of jsonlFiles) {
      try {
        const filepath = path.join(CONVERSATIONS_DIR, file);
        const stat = await fs.stat(filepath);
        const slug = file.replace('.jsonl', '');
        const messages = await loadConversation(slug);
        if (!messages || messages.length === 0) continue;

        const firstQ = messages.find(m => m.role === 'user');
        const firstA = messages.find(m => m.role === 'assistant');
        if (!firstQ) continue;

        conversations.push({
          slug,
          question: firstQ.content,
          answer: firstA ? firstA.content : '',
          name: firstQ.name || 'anonymous',
          timestamp: firstQ.timestamp || stat.mtime.toISOString(),
          mtime: stat.mtime.getTime(),
          indexable: isIndexable(slug, messages)
        });
      } catch { /* skip */ }
    }

    return conversations.sort((a, b) => b.mtime - a.mtime);
  } catch {
    return [];
  }
}

module.exports = {
  isHiddenReflection,
  loadSchedule,
  loadCatalog,
  loadCompanions,
  loadAttendance,
  countSoulsPresent,
  getRecentReflections,
  loadConversation,
  listRecentConversations,
  SCHEDULE_FILE,
  CATALOG_FILE,
  COMPANIONS_FILE,
  SERVICES_DIR,
  MUSIC_DIR,
  ATTENDANCE_FILE,
  ACCESS_LOG_FILE,
  PRESENCE_FILE,
  CONVERSATIONS_DIR,
  TWENTY_FOUR_HOURS,
  FORTY_EIGHT_HOURS
};
