#!/usr/bin/env node
/**
 * Write a new piece from what Moltbook is saying.
 *
 * Plan: docs/plans/moltbook-songwriting-2026-08-15.md
 *
 *   node scripts/generate-song.js --dry-run   listen and write nothing
 *   node scripts/generate-song.js             listen, write, commit
 *
 * The generate module produces artifacts and never touches the filesystem.
 * This script is the only thing that writes, and it writes exactly the paths
 * the paths module computed: there is no git add -A anywhere in it, so a file
 * that appears for any other reason is not swept along.
 */

const fs = require('fs').promises;
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');

require('dotenv').config({ path: path.join(__dirname, '../.env') });

const generate = require('../server/lib/song-generation/generate');
const { PROJECT_ROOT } = require('../server/lib/song-generation/paths');
const { updateReadme } = require('../server/lib/content-generation/update-readme');
const { readModifyWriteJSON } = require('../server/lib/utils/safe-json');
const { appendLog } = require('../server/lib/content-generation/log');

const execFileAsync = promisify(execFile);
const DRY_RUN = process.argv.includes('--dry-run');

function today() {
  return new Date().toISOString().slice(0, 10);
}

async function git(args) {
  const { stdout } = await execFileAsync('git', args, { cwd: PROJECT_ROOT });
  return stdout.trim();
}

/**
 * Write the four files.
 *
 * The lastmod manifest is updated in place rather than by regenerating it:
 * generate-docs-lastmod.js derives dates from git history, and this document
 * has no history yet, so regenerating would leave it out.
 */
async function writeArtifacts(result) {
  const { paths, document, songContent, decision } = result;
  const written = [];

  await fs.mkdir(path.dirname(paths.absolute.song), { recursive: true });
  await fs.writeFile(paths.absolute.song, songContent, 'utf8');
  written.push(paths.relative.song);

  await fs.writeFile(paths.absolute.document, document, 'utf8');
  written.push(paths.relative.document);

  const readme = await updateReadme(
    paths.category, decision.title, paths.slug, '🕯️', document, PROJECT_ROOT,
  );
  if (readme) {
    await fs.writeFile(paths.absolute.readme, readme.content, 'utf8');
    written.push(paths.relative.readme);
  }

  // Signature is (filepath, defaultValue, mutate). Getting that order wrong
  // passes the mutator as the default and an object as the callback, and fails
  // at call time with "mutate is not a function".
  await readModifyWriteJSON(paths.absolute.lastmod, {}, (manifest) => {
    manifest[paths.relative.document] = today();
    // Keep the manifest sorted, the way the generator emits it, so the diff is
    // one line rather than a reshuffle.
    return Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
  });
  written.push(paths.relative.lastmod);

  return written;
}

/**
 * Commit, crediting the channels rather than the individual authors.
 *
 * No agent posting in a public channel consented to being a songwriting input,
 * and the fellowship protocol's care and dignity axiom points away from naming
 * them. The submolts and the date are enough to trace where a piece came from.
 */
async function commit(result, written) {
  const { decision, paths, posts } = result;
  const channels = [...new Set(posts.map((p) => p.submolt).filter(Boolean))].sort();

  const message = `Add ${decision.form}: ${decision.title}

Written in response to what agents were discussing on Moltbook.
Channels listened to: ${channels.join(', ')}
Posts considered: ${posts.length}

${decision.rationale}

Generated by scripts/generate-song.js. Plan:
docs/plans/moltbook-songwriting-2026-08-15.md`;

  await git(['add', '--', ...written]);

  const staged = (await git(['diff', '--cached', '--name-only'])).split('\n').filter(Boolean);
  const unexpected = staged.filter((f) => !written.includes(f));
  if (unexpected.length) {
    // The four-path invariant. Something else was already staged, and
    // committing here would sweep it into a song commit.
    throw new Error(`Refusing to commit: unexpected staged files: ${unexpected.join(', ')}`);
  }

  await git(['commit', '-m', message]);
  return git(['rev-parse', '--short', 'HEAD']);
}

function preview(result) {
  const { decision, paths, document, song } = result;

  console.log(`\n${'='.repeat(70)}`);
  console.log(`${decision.form.toUpperCase()}: ${decision.title}`);
  console.log(`${'='.repeat(70)}`);
  console.log(`\nAngle: ${decision.angle}`);
  console.log(`\nWould write ${paths.count} paths:`);
  for (const rel of Object.values(paths.relative)) console.log(`  ${rel}`);

  console.log(`\n--- ${paths.relative.document} (first 900 chars) ---`);
  console.log(document.slice(0, 900));

  console.log(`\n--- style prompt ---`);
  console.log(song.style);

  console.log(`\n--- lyrics (first 900 chars) ---`);
  console.log(song.lyrics.slice(0, 900));
  console.log();
}

async function main() {
  const started = Date.now();
  console.log(DRY_RUN ? 'DRY RUN: nothing will be written.\n' : 'Live run.\n');

  const result = await generate.run();

  if (!result.ready) {
    console.log(`\nNo piece written (${result.stage}): ${result.reason}`);
    if (result.problems) process.exitCode = 1;
    await appendLog({
      kind: 'song-generation',
      outcome: `skip:${result.stage}`,
      reason: result.reason,
      durationMs: Date.now() - started,
    }).catch(() => {});
    return;
  }

  preview(result);

  if (DRY_RUN) {
    console.log('Dry run: no files written, nothing committed.');
    return;
  }

  const written = await writeArtifacts(result);
  console.log(`Wrote ${written.length} files.`);

  const sha = await commit(result, written);
  console.log(`Committed ${sha}.`);

  await appendLog({
    kind: 'song-generation',
    outcome: 'wrote',
    slug: result.paths.slug,
    form: result.decision.form,
    commit: sha,
    durationMs: Date.now() - started,
  }).catch(() => {});
}

main().catch((error) => {
  console.error(`\nRun failed: ${error.message}`);
  process.exitCode = 1;
});
